export type EuropeanCountry = {
  name: string;
  code: string;
  dialCode: string;
  flagColors: string[];
  flagPattern: "vertical" | "horizontal";
};

export const europeanCountries: EuropeanCountry[] = [
  {
    name: "Germania",
    code: "DE",
    dialCode: "+49",
    flagColors: ["#111827", "#ef4444", "#facc15"],
    flagPattern: "horizontal",
  },
  {
    name: "România",
    code: "RO",
    dialCode: "+40",
    flagColors: ["#2563eb", "#facc15", "#ef4444"],
    flagPattern: "vertical",
  },
  {
    name: "Austria",
    code: "AT",
    dialCode: "+43",
    flagColors: ["#ef4444", "#ffffff", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Franța",
    code: "FR",
    dialCode: "+33",
    flagColors: ["#2563eb", "#ffffff", "#ef4444"],
    flagPattern: "vertical",
  },
  {
    name: "Italia",
    code: "IT",
    dialCode: "+39",
    flagColors: ["#16a34a", "#ffffff", "#ef4444"],
    flagPattern: "vertical",
  },
  {
    name: "Spania",
    code: "ES",
    dialCode: "+34",
    flagColors: ["#ef4444", "#facc15", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Portugalia",
    code: "PT",
    dialCode: "+351",
    flagColors: ["#16a34a", "#ef4444", "#ef4444"],
    flagPattern: "vertical",
  },
  {
    name: "Olanda",
    code: "NL",
    dialCode: "+31",
    flagColors: ["#ef4444", "#ffffff", "#2563eb"],
    flagPattern: "horizontal",
  },
  {
    name: "Belgia",
    code: "BE",
    dialCode: "+32",
    flagColors: ["#111827", "#facc15", "#ef4444"],
    flagPattern: "vertical",
  },
  {
    name: "Danemarca",
    code: "DK",
    dialCode: "+45",
    flagColors: ["#ef4444", "#ffffff", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Suedia",
    code: "SE",
    dialCode: "+46",
    flagColors: ["#2563eb", "#facc15", "#2563eb"],
    flagPattern: "vertical",
  },
  {
    name: "Norvegia",
    code: "NO",
    dialCode: "+47",
    flagColors: ["#ef4444", "#ffffff", "#2563eb"],
    flagPattern: "horizontal",
  },
  {
    name: "Finlanda",
    code: "FI",
    dialCode: "+358",
    flagColors: ["#ffffff", "#2563eb", "#ffffff"],
    flagPattern: "vertical",
  },
  {
    name: "Polonia",
    code: "PL",
    dialCode: "+48",
    flagColors: ["#ffffff", "#ffffff", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Cehia",
    code: "CZ",
    dialCode: "+420",
    flagColors: ["#2563eb", "#ffffff", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Slovacia",
    code: "SK",
    dialCode: "+421",
    flagColors: ["#ffffff", "#2563eb", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Ungaria",
    code: "HU",
    dialCode: "+36",
    flagColors: ["#ef4444", "#ffffff", "#16a34a"],
    flagPattern: "horizontal",
  },
  {
    name: "Bulgaria",
    code: "BG",
    dialCode: "+359",
    flagColors: ["#ffffff", "#16a34a", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Grecia",
    code: "GR",
    dialCode: "+30",
    flagColors: ["#2563eb", "#ffffff", "#2563eb"],
    flagPattern: "horizontal",
  },
  {
    name: "Irlanda",
    code: "IE",
    dialCode: "+353",
    flagColors: ["#16a34a", "#ffffff", "#f97316"],
    flagPattern: "vertical",
  },
  {
    name: "Croația",
    code: "HR",
    dialCode: "+385",
    flagColors: ["#ef4444", "#ffffff", "#2563eb"],
    flagPattern: "horizontal",
  },
  {
    name: "Slovenia",
    code: "SI",
    dialCode: "+386",
    flagColors: ["#ffffff", "#2563eb", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Estonia",
    code: "EE",
    dialCode: "+372",
    flagColors: ["#2563eb", "#111827", "#ffffff"],
    flagPattern: "horizontal",
  },
  {
    name: "Letonia",
    code: "LV",
    dialCode: "+371",
    flagColors: ["#991b1b", "#ffffff", "#991b1b"],
    flagPattern: "horizontal",
  },
  {
    name: "Lituania",
    code: "LT",
    dialCode: "+370",
    flagColors: ["#facc15", "#16a34a", "#ef4444"],
    flagPattern: "horizontal",
  },
  {
    name: "Luxemburg",
    code: "LU",
    dialCode: "+352",
    flagColors: ["#ef4444", "#ffffff", "#38bdf8"],
    flagPattern: "horizontal",
  },
  {
    name: "Elveția",
    code: "CH",
    dialCode: "+41",
    flagColors: ["#ef4444", "#ffffff", "#ef4444"],
    flagPattern: "vertical",
  },
];
