const signaturePalette = {
  charcoal: "#101214",
  charcoalSoft: "#171A1D",
  charcoalElevated: "#202428",
  ivory: "#F4F0E7",
  ivorySurface: "#FAF7F0",
  ivoryElevated: "#FFFDF8",
  warmGraySurface: "#EDE7DB",
  warmGrayInteractive: "#F7F2E8",
  warmGrayDisabled: "#E8E1D6",
  warmGrayBorder: "#D8D1C4",
  warmGrayBorderMuted: "#E5DED2",
  warmGrayBorderStrong: "#8C8377",
  ink: "#191A1C",
  inkSecondary: "#494744",
  inkMuted: "#6B665E",
  inkDisabled: "#7A746B",
  ivoryOnDark: "#F4F0E7",
  ivoryOnDarkSecondary: "#D2CDC3",
  ivoryOnDarkMuted: "#ABA59B",
  gold: "#A98538",
  goldHover: "#D0AF63",
  goldPressed: "#A47E2E",
  goldMuted: "#E9DDBF",
  goldFocus: "#9C7727",
  green: "#287052",
  amber: "#8A570B",
  red: "#9F2D32",
  blue: "#245F86",
} as const;

/**
 * RabAI Signature semantic colors.
 *
 * Product UI should consume role names from this object, never raw palette
 * values. The aliases at the bottom remain temporarily available while older
 * screens migrate to the canonical roles.
 */
export const Colors = {
  shellBackground: signaturePalette.charcoal,
  shellSurface: signaturePalette.charcoalSoft,
  shellElevated: signaturePalette.charcoalElevated,
  canvas: signaturePalette.ivory,
  surface: signaturePalette.ivorySurface,
  surfaceMuted: signaturePalette.warmGraySurface,
  surfaceElevated: signaturePalette.ivoryElevated,

  textPrimary: signaturePalette.ink,
  textSecondary: signaturePalette.inkSecondary,
  textMuted: signaturePalette.inkMuted,
  textOnDark: signaturePalette.ivoryOnDark,

  border: signaturePalette.warmGrayBorder,
  borderStrong: signaturePalette.warmGrayBorderStrong,

  goldPrimary: signaturePalette.gold,
  goldHover: signaturePalette.goldHover,
  goldPressed: signaturePalette.goldPressed,
  goldMuted: signaturePalette.goldMuted,
  focusRing: signaturePalette.goldFocus,

  success: signaturePalette.green,
  warning: signaturePalette.amber,
  danger: signaturePalette.red,
  information: signaturePalette.blue,

  // Supporting semantic roles.
  surfaceInteractive: signaturePalette.warmGrayInteractive,
  surfaceDisabled: signaturePalette.warmGrayDisabled,
  borderMuted: signaturePalette.warmGrayBorderMuted,
  textDisabled: signaturePalette.inkDisabled,
  placeholder: signaturePalette.inkMuted,
  link: signaturePalette.blue,
  onPrimary: signaturePalette.ink,
  onDanger: signaturePalette.ivoryElevated,
  onSuccess: signaturePalette.ivoryElevated,
  focusRingSoft: "rgba(156, 119, 39, 0.24)",
  selection: signaturePalette.goldMuted,
  skeleton: "#DED6C9",
  overlay: "rgba(16, 18, 20, 0.54)",
  overlayStrong: "rgba(16, 18, 20, 0.76)",

  successSurface: "#E4F0E9",
  successBorder: "#91B4A1",
  warningSurface: "#F7EBD6",
  warningBorder: "#C8A875",
  dangerHover: "#89252B",
  dangerPressed: "#741F24",
  dangerSurface: "#F8E7E5",
  dangerBorder: "#D39C9A",
  informationSurface: "#E5EEF2",
  informationBorder: "#9DB6C1",

  // Compatibility aliases. New code must use the semantic roles above.
  background: signaturePalette.ivory,
  backgroundPlain: signaturePalette.ivorySurface,
  surfaceInverse: signaturePalette.charcoal,
  surfaceInverseMuted: "rgba(244, 240, 231, 0.10)",
  surfaceInverseSubtle: "rgba(244, 240, 231, 0.14)",
  surfaceInverseElevated: "rgba(32, 36, 40, 0.94)",
  borderNeutral: signaturePalette.warmGrayBorder,
  borderInverse: "rgba(244, 240, 231, 0.20)",
  borderInverseStrong: "rgba(244, 240, 231, 0.32)",
  borderOnInverse: "rgba(16, 18, 20, 0.36)",
  textBody: signaturePalette.ink,
  textSubtle: signaturePalette.inkSecondary,
  textOnInverse: signaturePalette.ivoryOnDark,
  textOnInverseSecondary: signaturePalette.ivoryOnDarkSecondary,
  textOnInverseMuted: signaturePalette.ivoryOnDarkMuted,
  primary: signaturePalette.gold,
  primaryHover: signaturePalette.goldHover,
  primaryPressed: signaturePalette.goldPressed,
  primarySoft: signaturePalette.goldMuted,
  accent: signaturePalette.goldPressed,
  accentSoft: signaturePalette.goldMuted,
  brand: signaturePalette.gold,
  brandDeep: signaturePalette.goldPressed,
  brandSoft: signaturePalette.goldMuted,
  brandOn: signaturePalette.ink,
  text: signaturePalette.ink,
  white: signaturePalette.ivoryElevated,
  black: signaturePalette.charcoal,
} as const;
