export const Spacing = {
  // Canonical RabAI Signature rhythm for new UI.
  micro: 2,
  compact: 4,
  control: 8,
  inline: 12,
  component: 16,
  content: 20,
  section: 24,
  page: 32,
  pageWide: 40,
  layout: 48,
  display: 64,

  // Compatibility aliases used by existing screens during rollout.
  none: 0,
  xxs: 2,
  xs: 4,
  detail: 5,
  sm: 6,
  md: 8,
  lg: 10,
  xl: 12,
  xxl: 14,
  three: 16,
  four: 18,
  five: 20,
  six: 22,
  screen: 24,
  seven: 28,
  eight: 32,
  icon: 54,
} as const;
